### PR TITLE
Add fund handling clause for compliance

### PR DESCRIPTION
**Pull request by wilt00**

### CODE REVIEW

**Review by alx168 — APPROVED** [review]
Approved with full vote from council.

**Comment by wilt00** [comment]
Requirements:

> Key Points of constitution:
> 
> 1) The Center for Student Involvement does not allow co or shared offices 
> 
> 2) No names should be included in the constitution 
> 
> Be sure to include the following in your constitution:
> 
> 1) Membership:  It is required that you include membership requirements word for word in your constitution. "__All requirements must meet the Board of trustee’s policies regarding nondiscrimination on the basis of race, color, religion, sex, national origin, ancestry, age, order of protection status, genetic information, marital status, disability, sexual orientation including gender identity, unfavorable discharge from the military or status as a protected veteran.__" 
> 
> 2) Handling of Funds: You must outline in this section which officers you’re allowing to handle funds.  Per Center for Student Involvement guidelines, information for the president, treasurer, and third officer of your choosing must be included in the registration submission. These officers will be the only members allowed to access the COF account. The advisor may not be the third officer. You may deem within your constitution that only 1 or 2 of the 3 officers can handle funds. 
> 
> 3) COF Account use  __All funds raised on campus MUST be deposited into the organization’s on-campus Chicago Organization Fund account.__ 
> 
> The text __underlined__ represents a information that should be included word for word.
>

**Comment by clee231** [comment]
I would suggest you speak with Theys about this... before making any drastic changes.

CSI has been changing rules year-after-year, which makes it increasingly difficult to deal with them.  Many College of Engineering Organizations have noted these difficulties to the college back in 2016.  Many student organization started a transition over to a "college initiative".  Many engineering clubs are still considered student organizations under the respective colleges themselves.  If you don't need CSI's resources, I'd say it's best to avoid them... but that's just my humble opinion.

I'll forward you guys some other email threads later...

**Comment by M-a-c** [comment]
I agree this is something to seriously think about. @clee231 thanks for passing on your knowledge with this.

**Comment by wilt00** [comment]
Superseded by #3

**Pull request closed without merging**
